apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapimongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todomongo
  template:
    metadata:
      labels:
        app: todomongo
    spec:
      containers:
      - name: todoapimongo
        image: padmanabhan1/todoapi-mongo:master
        env:
        - name: MONGO_HOST
          value: svcmongo.default.svc.cluster.local
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svctodomongoapi
spec:
  type: NodePort
  selector:
    app: todomongo
  ports:
  - port: 8081
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_DATABASE
          value: tododb
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: svcmongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
